service: lanista-coach-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  memorySize: 512

plugins:
  - serverless-nextjs-plugin
  - serverless-offline

custom:
  serverless-nextjs:
    staticDir: ./static
    routes:
      - src: post
        path: post/{slug}
        request:
          parameters:
            paths:
              slug: true

package:
  exclude:
    - ./**
